### ISSUE TITLE
python_requires not supported

### ISSUE THREAD

**Issue by sunj1** [conan-io/conan-package-tools#253]
conan 1.7.1 has a python_requires module which helps to re-use python recipes in conan files

https://docs.conan.io/en/latest/mastering/python_requires.html#python-requires

Error while using this feature:
```
Traceback (most recent call last):
  File "build.py", line 31, in <module>
    builder = ConanMultiPackager(username=username,channel=channel, stable_channel=channel)
  File "/usr/lib/python2.7/site-packages/cpt/packager.py", line 164, in __init__
    conanfile = load_cf_class("./conanfile.py")
  File "/usr/lib/python2.7/site-packages/cpt/packager.py", line 34, in load_cf_class
    return loader.load_class(path)
  File "/usr/lib/python2.7/site-packages/conans/client/loader.py", line 46, in load_class
    loaded, filename = _parse_file(conanfile_path)
  File "/usr/lib/python2.7/site-packages/conans/client/loader.py", line 256, in _parse_file
    '\n'.join(trace[3:])))
conans.errors.ConanException: Unable to load conanfile in ./conanfile.py
  File "./conanfile.py", line 3, in <module>
    base = python_requires("MyBase/1.7@demo/test")
  File "/usr/lib/python2.7/site-packages/conans/client/graph/python_requires.py", line 31, in __call__
    self._range_resolver.resolve(requirement, "python_require", update=False,
AttributeError: 'NoneType' object has no attribute 'resolve'
```

**Comment by lasote** [comment]
I've released 0.18.6 version, please relaunch, check that latest CPT is installed and report! thanks.

**Comment by sunj1** [comment]
I did `pip install --upgrade conan_package_tools` and installed `Version: 0.19.0`
Below issue came up:
```
[conan_create]
Traceback (most recent call last):
  File "build.py", line 102, in <module>
    builder.run()
  File "/usr/lib/python2.7/site-packages/cpt/packager.py", line 393, in run
    self.run_builds(base_profile_name=base_profile_name)
  File "/usr/lib/python2.7/site-packages/cpt/packager.py", line 470, in run_builds
    r.run()
  File "/usr/lib/python2.7/site-packages/cpt/runner.py", line 54, in run
    name, version, user, channel = self._reference
TypeError: 'NoneType' object is not iterable
```

**Comment by sunj1** [comment]
I checked that conan has an upgrade as well (1.7.2) and updated it.
Still the same issue.
Not sure if it's a new one or related.

**Comment by lasote** [comment]
It is definitely a new one, but related. Aren't you passing a "reference" parameter or CONAN_REFERENCE env var with name/version, right? e.j: `lib/1.0`
It usually tries to read it from the `conanfile.py` and it is not able right now because of the python requirements. Try to pass it, I can try to load the python requires to load the class and extract the name and version.

**Comment by sunj1** [comment]
I tried passing the reference "MyPkg/1.0" to the `add()`, but then again the original issue comes up
```
  File "/usr/lib/python2.7/site-packages/conans/client/graph/python_requires.py", line 31, in __call__
    self._range_resolver.resolve(requirement, "python_require", update=False,
AttributeError: 'NoneType' object has no attribute 'resolve'
```

**Comment by lasote** [comment]
That is very weird. Nevermind, try now, I've just released 0.19.1

**Comment by sunj1** [comment]
Looks like the pipeline is still running.
I will patch my code try

**Comment by sunj1** [comment]
I patched it and it works (even without passing reference).
Thanks for the quick fix.

Could you also let me know how to enable `update=True` in call to `self._range_resolver.resolve()`

**Comment by lasote** [comment]
> Could you also let me know how to enable update=True in call to self._range_resolver.resolve()
What do you need exactly?

**Comment by lasote** [comment]
It is not currently possible. I suggest opening a new issue as it is not a bug but an enhancement. Related to https://github.com/conan-io/conan-package-tools/issues/240

**Comment by sunj1** [comment]
Will wait for #240 to be fixed.
Thanks.
