### ISSUE TITLE
Add lasote/conanclang39 capability

### ISSUE THREAD

**Issue by lasote** [conan-io/conan-package-tools#69]

**Comment by uilianries** [comment]
Done!

**Comment by Croydon** [comment]
@uilianries Just a small hint: You could use language like "fix #69" or "close #69" in your PR title to directly close issues, when the PR gets merged.

Aaaaad, thanks for your work :)

**Comment by memsharded** [comment]
Thanks @Croydon for the tip. I knew it, it works even if put as a comment in the PR. 
The only thing is that we try to avoid it, so issues remain open until they are released (then manually closed), not when they are merged. It was a bit confusion for users to see an issue closed and marked as fixed, but still failing for them.

**Comment by uilianries** [comment]
@Croydon Thanks for the tip :smile:
